// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shopping/internal/server"
)

// Injectors from wire.go:

func NewUserGrpc() *server.UserServer {
	userServer := server.NewUserServer()
	return userServer
}
