version: '3.0'
services:
  mysql:
    image: 'mysql:8.0.29'
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      # 初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13306:3306"
  consul:
    image: 'consul:1.15.4'
    container_name: consul
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600/udp"
    command: ["agent", "-dev", "-client=0.0.0.0"]
  redis:
    container_name: redis
    image: 'bitnami/redis:7.2.4'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'