// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shopping/internal/server"
)

// Injectors from wire.go:

func NewGoodGrpc() *server.GoodServer {
	goodServer := server.NewGoodServer()
	return goodServer
}
