// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"shopping/internal/biz"
	"shopping/pkg/consul/connect"
)

// Injectors from wire.go:

func NewUserHttpServer() *gin.Engine {
	userClient := connect.NewUserGrpc()
	userHandler := biz.NewUserHandler(userClient)
	engine := biz.NewUserGin(userHandler)
	return engine
}
