// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"shopping/internal/service"
)

// Injectors from wire.go:

func NewUserHttpServer() *gin.Engine {
	engine := service.NewUserGin()
	return engine
}
