// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"shopping/config"
	"shopping/internal/biz"
	"shopping/internal/middlewares"
	"shopping/internal/middlewares/jwt"
	"shopping/pkg/consul/connect"
)

// Injectors from wire.go:

func NewUserHttpServer() *gin.Engine {
	userClient := connect.NewUserGrpc()
	smsClient := connect.NewSmsGrpc()
	cmdable := config.NewRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	userHandler := biz.NewUserHandler(userClient, smsClient, handler)
	goodHandler := biz.NewGoodHandler()
	v := middlewares.NewMiddlewares(handler)
	engine := biz.NewUserGin(userHandler, goodHandler, v)
	return engine
}
