// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shopping/config"
	"shopping/internal/server"
)

// Injectors from wire.go:

func NewSmsGrpc() *server.SmsServer {
	cmdable := config.NewRedis()
	smsServer := server.NewSmsServer(cmdable)
	return smsServer
}
