db:
  mysql: "root:root@tcp(127.0.0.1:13306)/shop?charset=utf8mb4&parseTime=True"
  redis: "localhost:16379"
consul:
  host: "127.0.0.1"
  port: 8500
user:
  http:
    host: "127.0.0.1"
    port: 8081
    service_name: "user-http"
  grpc:
    host: "127.0.0.1"
    service_name: "user-grpc"
    tags: ["user", "grpc"]
sms:
  grpc:
    host: "127.0.0.1"
    service_name: "sms-grpc"
    tags: [ "sms", "grpc" ]
good:
  grpc:
    host: "127.0.0.1"
    service_name: "good-grpc"
    tags: [ "good", "grpc" ]