// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInventory = "inventory"

// Inventory mapped from table <inventory>
type Inventory struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GoodID int64 `gorm:"column:good_id;comment:商品id" json:"good_id"` // 商品id
	Stock  int32 `gorm:"column:stock;comment:库存" json:"stock"`       // 库存
}

// TableName Inventory's table name
func (*Inventory) TableName() string {
	return TableNameInventory
}
